# Generated by Django 4.0 on 2022-01-31 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=12)),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state')),
                ('zipCode', models.CharField(blank=True, max_length=100, verbose_name='zipCode')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='contacto')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='notes')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('is_pro', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
