# Generated by Django 4.0 on 2022-01-31 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='description')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state')),
                ('zipCode', models.CharField(blank=True, max_length=100, verbose_name='zipCode')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='contacto')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='notes')),
                ('email', models.EmailField(blank=True, max_length=70, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=250, verbose_name='phone')),
                ('url_corp', models.CharField(blank=True, max_length=250, verbose_name='url')),
                ('feeds', models.CharField(blank=True, max_length=250, verbose_name='feeds')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_owner', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='description')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state')),
                ('zipcode', models.CharField(blank=True, max_length=100, verbose_name='zipcode')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='contacto')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='notes')),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('phone', models.CharField(blank=True, max_length=250, verbose_name='phone')),
                ('url_corp', models.CharField(blank=True, max_length=250, verbose_name='url')),
                ('feeds', models.CharField(blank=True, max_length=250, verbose_name='feeds')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costos.company')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='description')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state')),
                ('zipCode', models.CharField(blank=True, max_length=100, verbose_name='zipCode')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='contacto')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='notes')),
                ('email', models.EmailField(blank=True, max_length=70, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=250, verbose_name='phone')),
                ('url_corp', models.CharField(blank=True, max_length=250, verbose_name='url')),
                ('feeds', models.CharField(blank=True, max_length=250, verbose_name='feeds')),
                ('chefs', models.ManyToManyField(related_name='restaurant_chef', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_manager', to='auth.user')),
                ('providers', models.ManyToManyField(to='costos.Provider')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='restaurants',
            field=models.ManyToManyField(to='costos.Restaurant'),
        ),
    ]
